# Generated by Django 4.1.2 on 2022-11-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecomplited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
